### PR TITLE
replacing deprecated koa-gzip with koa-compress

### PR DESCRIPTION
**Pull request by dj-hedgehog**
koa-gzip was deprecrated today. I exchanged it with koa-compress and replaced the koa-gzip tests with the koa-compress ones.

### CODE REVIEW

**Comment by loicsaintroch** [comment]
Awesome thank you very much @dj-hedgehog for this kind update. Maybe we should rename the `gzip` config to `compress` don't you think?

**Comment by dj-hedgehog** [comment]
@loicsaintroch I thought about that too but then didn't do it because essentially what the plugin does is gzipping the output. I think that having the option called `gzip`make is instantly clear what it is doing. `compress` is a little bit more abstract.

Ultimately if you want it to be called `compress` just say the word!

**Comment by loicsaintroch** [comment]
Ok I understand. No, you're right @dj-hedgehog it's easier to understand like this. Do you know why the tests fail?

**Comment by loicsaintroch** [comment]
Hey @dj-hedgehog, can you please make another PR on the `v2` branch please?

**Comment by dj-hedgehog** [comment]
Voilá #98 :shipit:

**Comment by loicsaintroch** [comment]
Thanks @dj-hedgehog

**Pull request closed without merging**
